### ISSUE TITLE
Please deploy this so that 2.17.2 link on the website works

### ISSUE THREAD

**Issue by shivammathur** [phingofficial/phingofficial.github.io#7]
Please deploy this so that `2.17.2` link on the phing.info website works.
https://www.phing.info/get/phing-2.17.2.phar

**Comment by mrook** [comment]
Fixed, thanks for the report

**Comment by mrook** [comment]
https://github.com/phingofficial/phingofficial.github.io/commit/d0afb44f75be68c3c32ec25c8ff402f38127045e

**Comment by shivammathur** [comment]
@mrook Thanks for fixing it quickly
